### ISSUE TITLE
panic on Apple M1

### ISSUE THREAD

**Issue by xyproto** [marten-seemann/qtls-go1.15#1]
When a Homebrew contributor tried to build [algernon](https://github.com/xyproto/algernon), that in turn uses `qtls-go1-15`, the contributor wrote:

> 👋  it looks like algernon 1.12.11 failed to build on apple silicon as error log show below:
> 
> ```
> /usr/bin/sandbox-exec -f /private/tmp/homebrew20210102-35928-hbkxt1.sb ruby -W0 -I $LOAD_PATH -- /opt/homebrew/Library/Homebrew/test.rb /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/algernon.rb --verbose
> panic: qtls.ClientHelloInfo doesn't match
> 
> goroutine 1 [running]:
> github.com/marten-seemann/qtls-go1-15.init.0()
> 	github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x1b4
> ==> curl -sIm3 -o- http://localhost:53111
> 
> Error: algernon: failed
> An exception occurred within a child process:
>   Test::Unit::AssertionFailedError: <0> expected but was
> <7>.
> ```
> 
> build error log, https://github.com/Homebrew/homebrew-core/runs/1638106915
> relates to https://github.com/Homebrew/homebrew-core/pull/68188

See also: https://github.com/xyproto/algernon/issues/49

Could it be that `qtls-go1-15` currently does not build on Apple M1 and are there plans to support it?

**Comment by marten-seemann** [comment]
Unfortunately, I don’t have an M1 Mac.
Would be happy to review a PR!

**Comment by ghost** [comment]
Same for FreeBSD
```shell
> ipfs-go -h
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
        github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x1e5
```

**Comment by margox** [comment]
> Same for FreeBSD
> 
> ```shell
> > ipfs-go -h
> panic: qtls.ClientHelloInfo doesn't match
> 
> goroutine 1 [running]:
> github.com/marten-seemann/qtls-go1-15.init.0()
>         github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x1e5
> ```

same for me :(

**Comment by ultra-pool** [comment]
Same for Ubuntu 20

```
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
	github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x132
```
go version go1.17.2 linux/amd64

**Comment by marten-seemann** [comment]
quic-go always supports the 2 most recent versions of Go. Therefore everything is working as intended here.

**Comment by xyproto** [comment]
@marten-seemann The version of Go is 1.17.2 in the comment from @ultra-pool.

**Comment by marten-seemann** [comment]
> @marten-seemann The version of Go is 1.17.2 in the comment from @ultra-pool.

Exactly, Go 1.17, Go 1.16 are the two most recent Go version. That's why qtls for Go 1.15 won't compile.

Really, there's nothing to fix here. Everything is working as intended.
